### PR TITLE
Transparent Youtube Logo

### LINKED ISSUE #85: 🐛 Bug: Find a truly transparent YouTube svg
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/SquiggleConf/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

In dark mode, the YouTube icon should have a transparent play button in the center... or failing that, a dark/black one. Not a white one.

### Actual

Looking at http://localhost:4321/about#squiggle-tools, we can see a white play button in the center:

Screenshot of the MiTS entry on About in dark mode, where the YouTube social link icon has a white play button

### Additional Info

I haven't looked at all for a better svg. The current one in the repo is https://github.com/SquiggleTools/SquiggleConf/blob/5e27fe307cb1e58014b76800bc3b96e79c0c58b1/src/assets/youtube.svg.

💖

### PR DESCRIPTION
**Pull request by abhijit360**
## PR Checklist

- [done ] Addresses an existing open issue: fixes #85 
- [done ] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/SquiggleConf/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [done] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/SquiggleConf/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
I found an online transparent svg and then used a tool online to change the colour #3A5A6E. The svg is transparent. However the colour isn't being appled for some reason

### CODE REVIEW

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Looks like this branch just has the `package-lock.json` addition, but not the actual YouTube logo itself?

I'd recommend reading through https://github.com/SquiggleTools/SquiggleConf/blob/main/.github/DEVELOPMENT.md to help with getting set up locally using pnpm. I'm guessing you're running `npm install` (or `npm i` for short), which isn't quite right for this repo.

Thanks! ✨

**Comment by JoshuaKGoldberg** [comment]
> [done ] Addresses an existing open issue: 

P.s. This should be `[x]`, not `[done ]`. It's an actual GitHub feature: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by JoshuaKGoldberg** [comment]
👋 @abhijit360 do you still have energy + time to work on this?

**Comment by abhijit360** [comment]
Yes! I will have the PR's in this week.

**Comment by JoshuaKGoldberg** [comment]
(talked offline: may have time later)

**Pull request closed without merging**
